name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: homolog

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: ssh-add
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        ssh-keyscan github.com > known_hosts
        chmod 600 id_rsa known_hosts
        git config --global url."https://oauth2:${{ secrets.TOKEN_GITHUB }}@github.com".insteadOf ssh://git@github.com

    - name: Terraform Init
      working-directory: terraform
      id: init
      run: terraform init

    - name: Terraform Format
      working-directory: terraform
      id: fmt
      run: terraform fmt -check

    - name: Terraform Plan
      working-directory: terraform
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -input=false

    - name: Terraform Apply
      working-directory: terraform
      # if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      if: github.event_name == 'pull_request'
      run: terraform apply -auto-approve -input=false
